Logging
duck-dynasty/duckbot pull request #208
Opened 2021-05-13 14:31 UTC by jameshughes89

Small change to enable logging. Code is more or less copy/pasteed from discord tutorial.

2021-05-13 14:31 UTC, twentylemon commented
Logging -> adds mp3 files. What?

2021-05-13 14:35 UTC, jameshughes89 commented
> Logging -> adds mp3 files. What?

Those were intended to be in a different branch (tito).

2021-05-13 14:37 UTC, Chippers255 commented
Respect the branch name brother.

2021-05-13 15:44 UTC, twentylemon commented on duckbot/__main__.py
> +logger.addHandler(handler)
1. Remove comments (also, discord-py is _not_ discord)
2. I don't think we want logs stored in files without log rotation/invalidation.
3. This shouldn't run outside of main

2021-05-13 15:45 UTC, twentylemon commented
> > Logging -> adds mp3 files. What?
> 
> Those were intended to be in a different branch (tito).

They are not related to _logging_, so remove them from this PR.

2021-05-13 16:57 UTC, jameshughes89 commented on duckbot/__main__.py
> +logger.addHandler(handler)
> 1. Remove comments (also, discord-py is _not_ discord)
> 2. I don't think we want logs stored in files without log rotation/invalidation.
> 3. This shouldn't run outside of main

This looks like a nice easy way to get log rotation: https://docs.python.org/3/library/logging.handlers.html#rotatingfilehandler

2021-05-13 16:58 UTC, twentylemon commented on duckbot/__main__.py
> +logger.addHandler(handler)
Brother, I believe in you. Cram it into this PR.

2021-05-13 19:13 UTC, jameshughes89 commented
All entirely untested.

2021-05-13 19:42 UTC, twentylemon reviewed
Looks much better! Almost like a real dev. 🚀 

I'd like to know the content of those logs before approval, we'll have to get you an api token.

2021-05-13 19:42 UTC, twentylemon commented on duckbot/__main__.py
> +    logger.setLevel(logging.DEBUG)
Given discord-py uses [gateway](https://discord.com/developers/docs/topics/gateway) events, debug is likely to be littered with a lot of heartbeat responses. I don't know if discord-py logs those at debug or info, this may even be better bumping up to warning. Something that will need to be tested. We'll get you a dev token at some point so you can dig a little deeper.

2021-05-13 19:42 UTC, twentylemon commented on duckbot/__main__.py
> +    # The choice of maxBytes=256000=250kB is arbitrary
Please remove comment. Inline comments such as this are meant to clarify complex logic or decisions. When I come back to this piece of code in two years, I'm not going to ask why the log file was capped to 250kb, so this comment is just noise I have to filter out.

2021-05-13 19:46 UTC, twentylemon requested changes

2021-05-13 19:46 UTC, twentylemon commented on duckbot/__main__.py
> +    handler = logging.RotatingFileHandler(filename="./logs/duck.log", mode="a", maxBytes=256000, backupCount=10)
Seems this is `logging.handlers.RotatingFileHandler`, see [sanity test](https://github.com/Chippers255/duckbot/runs/2578419360#step:3:950) and [docs](https://docs.python.org/3/library/logging.handlers.html#rotatingfilehandler)

2021-05-13 20:01 UTC, jameshughes89 commented on duckbot/__main__.py
> +    logger.setLevel(logging.DEBUG)
`2021-05-09 16:10:26,342:DEBUG:discord.http: GET https://discord.com/api/v7/gateway with None has returned 200
2021-05-09 16:10:26,343:DEBUG:discord.http: GET https://discord.com/api/v7/gateway has received {'url': 'wss://gateway.discord.gg'}
2021-05-09 16:10:26,551:DEBUG:discord.gateway: Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
2021-05-09 16:10:26,551:DEBUG:discord.client: Dispatching event socket_raw_receive
2021-05-09 16:10:26,551:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 10, 'd': {'heartbeat_interval': 41250, '_trace': ['["gateway-prd-main-vf9c",{"micros":0.0}]']}}
2021-05-09 16:10:26,552:DEBUG:discord.client: Dispatching event socket_response
2021-05-09 16:10:26,552:DEBUG:discord.client: Dispatching event socket_raw_send
2021-05-09 16:10:26,552:DEBUG:discord.client: Dispatching event socket_raw_send
2021-05-09 16:10:26,553:INFO:discord.gateway: Shard ID None has sent the IDENTIFY payload.
2021-05-09 16:10:26,633:DEBUG:discord.client: Dispatching event socket_raw_receive
2021-05-09 16:10:26,633:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}`

Example debug level output above. Literally says `heartbeat` --- good call.

2021-05-13 20:04 UTC, twentylemon commented on duckbot/__main__.py
> +    logger.setLevel(logging.DEBUG)
debug is also logging every api call, I don't think we really need request level logging. INFO is probably fine for now, we can also revisit in the future.

2021-05-13 20:09 UTC, jameshughes89 commented on duckbot/__main__.py
> +    logger.setLevel(logging.DEBUG)
Agreed. INFO also seems overkill, but not too verbose.

2021-05-13 20:09 UTC, jameshughes89 commented on duckbot/__main__.py
> +    # The choice of maxBytes=256000=250kB is arbitrary
What would a reasonable log file size cap be?

2021-05-13 20:13 UTC, twentylemon commented on duckbot/__main__.py
> +    # The choice of maxBytes=256000=250kB is arbitrary
More of a @Chippers255 question. It's his hardware. ~4mb though (10 x 250kb), seems fine as is. That probably ends up being quite a long time range stored in logs, given we don't really have a huge amount of interactions.

2021-05-13 21:19 UTC, twentylemon requested changes

2021-05-13 21:19 UTC, twentylemon commented on duckbot/__main__.py
> +    handler = logging.handlers.RotatingFileHandler(filename="./logs/duck.log", mode="a", maxBytes=256000, backupCount=10)
Checks still failing, guessing it doesn't like the `logs` directory. I imagine the append writing mode would create the log files, but not intermediary directories.

The only stuff in `.` is `duckbot`, `resources` and `requirements.txt`, so we're probably safe to simply use `duck.log` -- or creating the intermediary directories.

Further, thinking more about this, we'll need to add the log files to gitignore, in case people run duckbot from outside of docker. Either the logs directory (if it's used), or `*.log*` should be added -- or both.

2021-05-13 21:21 UTC, jameshughes89 commented on duckbot/__main__.py
> +    handler = logging.handlers.RotatingFileHandler(filename="./logs/duck.log", mode="a", maxBytes=256000, backupCount=10)
I like the idea of creating the logs dir with .gitignore.

2021-05-13 21:49 UTC, jameshughes89 commented
`makedirs()` will recursively make directories, which is unnecessary.

2021-05-13 21:58 UTC, Chippers255 commented on duckbot/__main__.py
> +    # The choice of maxBytes=256000=250kB is arbitrary
There is more than enough space on the SD card so 250kb is fine.

2021-05-13 22:00 UTC, twentylemon commented on .gitignore
> +logs/**
Just `logs` should work.

2021-05-13 22:00 UTC, twentylemon commented on duckbot/__main__.py
> +        os.mkdir(log_directory)
Minor, [os.mkdirs](https://docs.python.org/3/library/os.html#os.makedirs) has `exist_ok` so you could skip the `if`

2021-05-13 22:03 UTC, jameshughes89 commented on duckbot/__main__.py
> +        os.mkdir(log_directory)
Good good

2021-05-14 13:23 UTC, twentylemon approved these changes
Looks good to me, brother.

WELCOME TO THE TEAM 🚀

2021-05-14 13:24 UTC, merged