Log not cog
duck-dynasty/duckbot pull request #214
Opened 2021-05-16 22:16 UTC by jameshughes89

`!logs` will return an archive of the logs. close #210 

Originally this was setup under cogs, but has been moved out to it's own category --- _logging_.

Eventually the setup for the logs and for overriding the `on_command_error` (to include exceptions in the duck.logs) will be moved to logging.

2021-05-16 23:00 UTC, twentylemon requested changes

2021-05-16 23:00 UTC, twentylemon commented on duckbot/logging/logs.py
> +        subprocess.call(self.compress_command)
Strongly prefer to stay in python whenever possible, `subprocess` makes assumptions about the state of the machine. For compressing the logs, python has [tarfile](https://docs.python.org/3.8/library/tarfile.html) or [zipfile](https://docs.python.org/3.8/library/zipfile.html) built-in.

2021-05-16 23:00 UTC, twentylemon commented on duckbot/logging/__init__.py
> +    bot.add_cog(GetLogs(bot))
This function is not tested. You can more or less copy one of the existing `test_setup.py` files from another extension.

2021-05-16 23:00 UTC, twentylemon commented on tests/logging/test_logs.py
> +    assert context.send.call_args.kwargs["file"].filename == "duck.logs"
Prefer to make as few assertions as possible in your tests, and make the assertion itself contain as much info as possible. When the tests fail, we want to know why without having to understand an assertion failure like _expected true but got false_.

Ideally here, you're only make one assertion, `context.send.assert_called_once_with(file=file)`. Though, it seems `discord.File` doesn't implement `==`, so we'll need a few in this case, but we can still improve the errors we'd get here. Maybe something like:
```python
context.send.assert_called_once()
assert context.send.call_args.kwargs["file"].filename == "duck.logs"
```

But, I'm not a big fan of that either. We could define our own equals, similar to how we did for [Embed](https://github.com/Chippers255/duckbot/blob/main/tests/conftest.py#L144-L160) (see #177). Patching in `==` and `str()` for file would allow use to do the much cleaner `context.send.assert_called_once_with(file=file)`, but comes with the caveat that we have to write `==` and `str()` for a class we don't own. But, `==` is fairly simple, instance check and check that `fp` and `filename` are equal; and `str()` is `str(join(fp, filename))`.

2021-05-16 23:00 UTC, twentylemon commented on tests/logging/test_logs.py
> +async def test_archive_sent(bot, context):
Test names should be of the format `test_<unit-under-test>_<expectation>`. Eg, this one could be `test_logs_sends_tarball_of_logs`.

2021-05-16 23:00 UTC, twentylemon commented on duckbot/logging/logs.py
> +        subprocess.call(["rm", self.log_archive_path])
Is this required (removing the tarball)? The logs are only ~4mb, the tarball is likely to be like ~5% of that size. Will subsequent `!logs` invocations overwrite the tarball?

2021-05-16 23:00 UTC, twentylemon commented on duckbot/logging/logs.py
> +class GetLogs(commands.Cog):
Please rename the file to match the sole symbol defined in it. `get_logs.py` or rename this class to `Logs`. If you change the file name, change the test file name to match as well.

2021-05-16 23:00 UTC, twentylemon commented on tests/logging/test_logs.py
> +    assert not os.path.exists(os.path.join(os.getcwd(), "logs.tar.gz"))
This `os` interactions need to be mocked out. Tests shouldn't have side effects!

2021-05-16 23:01 UTC, twentylemon commented
Did you perform any manual testing? Can you include some examples for posterity?

2021-05-16 23:12 UTC, twentylemon commented on tests/logging/test_logs.py
> +    assert context.send.call_args.kwargs["file"].filename == "duck.logs"
> But, I'm not a big fan of that either.

I should be clear, the `eq` and `str` changes are larger, and maybe beyond the scope of this PR. Could be a follow up. For this making better assertions is good enough, though I won't poo-poo if you opt for the larger change.

2021-05-17 00:49 UTC, jameshughes89 commented on duckbot/logging/logs.py
> +        subprocess.call(["rm", self.log_archive_path])
I flip-flopped. No real preference either way. More did it to play with tests.

2021-05-17 00:51 UTC, jameshughes89 commented on duckbot/logging/logs.py
> +        subprocess.call(self.compress_command)
Done. Also, switched to `os.remove`.

2021-05-17 00:51 UTC, jameshughes89 commented on duckbot/logging/__init__.py
> +    bot.add_cog(GetLogs(bot))
Done.

2021-05-17 00:54 UTC, jameshughes89 commented on tests/logging/test_logs.py
> +async def test_archive_sent(bot, context):
Done.

2021-05-17 00:58 UTC, jameshughes89 commented on duckbot/logging/logs.py
> +class GetLogs(commands.Cog):
Done.

2021-05-17 15:02 UTC, jameshughes89 commented on duckbot/logging/logs.py
> +        subprocess.call(["rm", self.log_archive_path])
I opted to not remove it.

2021-05-17 15:03 UTC, jameshughes89 commented on tests/logging/test_logs.py
> +    assert not os.path.exists(os.path.join(os.getcwd(), "logs.tar.gz"))
Irrelevant now as the remove has been cut.

2021-05-17 15:09 UTC, jameshughes89 commented on tests/logging/test_logs.py
> +    assert context.send.call_args.kwargs["file"].filename == "duck.logs"
Changed to suggested assertion. 

RE: defining our own `== ` and `str()`, where do we feel is the best place to write this?

2021-05-17 15:24 UTC, jameshughes89 commented on tests/logging/test_logs.py
> +    assert context.send.call_args.kwargs["file"].filename == "duck.logs"
I assumed `fp` was a filepath, but it's actually an `_io.BufferedReader`. 

I do not believe we can easily compare `fp` values. We can compare `a.fp.read() == b.fp.read()` however, but that may be overkill. 

Below is an example:
```
In [4]: a = discord.file.File('logs.tar.gz')

In [5]: b = discord.file.File('logs.tar.gz')

.
.
.

In [10]: a.fp
Out[10]: <_io.BufferedReader name='logs.tar.gz'>

In [11]: type(a.fp)
Out[11]: _io.BufferedReader

In [12]: a.fp == b.fp
Out[12]: False

.
.
.
In [31]: a.fp.read() == b.fp.read()
Out[31]: True

```

2021-05-17 15:46 UTC, twentylemon commented on tests/logging/test_logs.py
> +    assert context.send.call_args.kwargs["file"].filename == "duck.logs"
That's annoying, I expected it to be a path-like object (like fp -> filepath). Reading the stream won't make sense in tests since the underlying file may not exist. In which case, I guess we can pass on defining `==` for now.

2021-05-17 16:00 UTC, jameshughes89 commented on tests/logging/test_logs.py
> +    assert context.send.call_args.kwargs["file"].filename == "duck.logs"
If we _really_ wanted, I suppose just compare file name attribute for `==` since that's all that we're currently doing in the test.

2021-05-19 18:52 UTC, twentylemon requested changes
Mocks! Huzzah!

2021-05-19 18:52 UTC, twentylemon commented on tests/logging/test_get_logs.py
> +@mock.patch("tarfile.open", autospec=True)
Can probably remove the `autospec` -- or at least fix `audospec`. `autospec` seems to me to be more for when you _use_ the mock a lot more; care about accessing fields that don't exist or you're stubbing a lot of behaviour. None of that is really happening here.

2021-05-19 18:52 UTC, twentylemon commented on tests/logging/test_get_logs.py
> +async def test_get_logs_sends_tarball_of_logs(mock_open, mock_dis_file, bot, context):
I'd drop `mock` from the names, the context already implies they are mocks. And `dis` means nothing, so just drop that too. `tar` or `open` and `file` are sufficient here.

2021-05-19 18:52 UTC, twentylemon commented on tests/logging/test_get_logs.py
> +    mock_open.add = mock.MagicMock()
This isn't quite right. You're stubbing a function, you don't want to add `tarfile.open.add`; rather, you want to change the `return_value` of `open`. Further, you should verify how this mock was interacted with. Your test now only checks `context.send` was called with a `discord.File`.

More correctly;

```python
@mock.patch("tarfile.open")
@mock.patch("tarfile.Tarfile") # or whatever type open returns
# rest left out for brevity
async def test(tar, open):
    open.return_value = tar
    # call !logs ; assert context.send ; essentially your existing test
    open.assert_called_once_with(log_dir, "w:gz")
    tar.add.assert_called_once_with(the_logs_directory)
    tar.close.assert_called_once()
```
The above verifies that a tarfile was created using the `log_dir`, in addition to sending the file.

_I think_ you could also even verify how the `discord.File` was constructed, which would pretty much capture everything going on in the unit under test.
```python
file.assert_called_once_with(tar_location, name)
```

2021-05-19 19:21 UTC, Chippers255 commented
This should return a clean archive. It currently returns the entire path to the logs. For example: `logs.tar.gz\home\jhughes\Insync\jameshughes89@gmail.com\Google Drive\codeProjects\duckBot\logs`

2021-05-19 19:29 UTC, jameshughes89 commented on tests/logging/test_get_logs.py
> +async def test_get_logs_sends_tarball_of_logs(mock_open, mock_dis_file, bot, context):
Made it discord_file instead of file because file is a type. Other than that, done.

2021-05-19 19:29 UTC, jameshughes89 commented on tests/logging/test_get_logs.py
> +@mock.patch("tarfile.open", autospec=True)
i like audospec

2021-05-19 20:19 UTC, twentylemon approved these changes
He has done it.

🚀

2021-05-20 14:14 UTC, merged