Record Exceptions in Logs
duck-dynasty/duckbot pull request #231
Opened 2021-05-21 19:39 UTC by jameshughes89

Record exceptions from commands in the log files. Currently this does **not** include any `on_message` exceptions, which I assume is possible, but that is outside the scope of this PR. Fixes #212

2021-05-21 19:57 UTC, twentylemon requested changes
What's the behaviour for `Cog.on_command_error`? Does it only respond to command errors in that cog? Or from the entire bot? I'm wondering if this new cog could simply add a listener to bot instance (similar to [on_ready](https://github.com/Chippers255/duckbot/blob/main/duckbot/duckbot.py#L24-L27)) which then applies to all command errors.

I'd also say this _does not_ fix #212. It's one part of it, we definitely want exceptions from events like `on_message` to be logged, as well as exceptions from `@task` methods.``

2021-05-21 19:57 UTC, twentylemon commented on duckbot/logging/exception_logs.py
> +        await self.__on_command_error(context, exception)
The private method thing here isn't required, you can invoke `@listener` methods directly in your tests. Also, imo prefer changing the name to describe the method's purpose, rather than the event it responds to. Ie:
```python
@commands.Cog.listener("on_command_error")
async def log_exceptions(self, context, exception):
    # blah
```

2021-05-21 19:57 UTC, twentylemon commented on duckbot/logging/exception_logs.py
> +            return
You're calling private methods here, definitely should not be doing that. Can you delegate this behaviour to `self.bot.on_command_error` maybe?

Do we ever really want to bail early from this? All we're doing is logging the exception. Seems to be we'd _always_ want that to happen.

2021-05-21 20:21 UTC, jameshughes89 commented
Based on tests, it responds to all command errors. 

Will look into the bot idea.

2021-05-21 20:24 UTC, jameshughes89 commented on duckbot/logging/exception_logs.py
> +            return
This is the overwritten method copy/pasted with two lines added for the logger. 

Would we ever want a specific error handler for a specific cog or something that has different behavior? Would we ever not want to log the exception?

2021-05-21 20:27 UTC, twentylemon commented on duckbot/logging/exception_logs.py
> +            return
I can't see any reason why we'd ever want to not log an exception. Invoking a cog specific error handler can still take place (presumably, that can be handled by the original method), but we may as well log all exceptions here so we don't have to remember to anywhere else.

2021-05-22 15:28 UTC, jameshughes89 commented
Although having it as a cog listener had it work for all cogs, I made it a listener for the whole bot. I was hoping this would magically make it work with messages too, but that was not the case.

2021-05-22 15:39 UTC, twentylemon commented
https://discordpy.readthedocs.io/en/latest/api.html#discord.on_error
> on_error will only be dispatched to Client.event().
> 
> It will not be received by Client.wait_for(), or, if used, Bots listeners such as listen() or listener().

So `listener` won't work (that's... odd). But seems `event` should? Could maybe try adding in `setup`:

```python
@bot.event
async def on_error(*args):
    log_it_bro()
```

2021-05-22 15:44 UTC, twentylemon commented
> Although having it as a cog listener had it work for all cogs, I made it a listener for the whole bot. I was hoping this would magically make it work with messages too, but that was not the case.

If it didn't work, I'd probably flip back to `@listener` then, just to keep the style consistent throughout all the cogs. The only weirdo that needs to use `add_listener` is the bot class itself.

2021-05-22 17:44 UTC, jameshughes89 commented
> https://discordpy.readthedocs.io/en/latest/api.html#discord.on_error
> 
> > on_error will only be dispatched to Client.event().
> > It will not be received by Client.wait_for(), or, if used, Bots listeners such as listen() or listener().
> 
> So `listener` won't work (that's... odd). But seems `event` should? Could maybe try adding in `setup`:
> 
> ```python
> @bot.event
> async def on_error(*args):
>     log_it_bro()
> ```

Tried to hack it in there with no success. 

I recommend addressing the `on_message` and `task` in a seperate PR as it seems to need some non insignificant tinkering.

2021-05-22 17:52 UTC, twentylemon approved these changes

2021-05-22 17:52 UTC, twentylemon commented on duckbot/logging/exception_logs.py
> +        print("Brother, ignoring exception in command {}:".format(context.command), file=sys.stderr)
Prefer f-strings to explicit `format` calls. This can be `f"Brother, ignoring exception in command {context.command}:"`

2021-05-22 17:52 UTC, twentylemon commented on tests/logging/test_exception_logs.py
> +    context.cog._get_overridden_method.return_value = None
Remove cog references? These seem like leftovers.

2021-05-22 17:59 UTC, jameshughes89 commented on tests/logging/test_exception_logs.py
> +    context.cog._get_overridden_method.return_value = None
Good catch. These were used for ensuring no early bailing on functio being tested.

2021-05-22 17:59 UTC, jameshughes89 commented on duckbot/logging/exception_logs.py
> +        print("Brother, ignoring exception in command {}:".format(context.command), file=sys.stderr)
Agreed. Changed.

2021-05-22 18:14 UTC, merged