Gitmoji standard
duck-dynasty/duckbot pull request #393
Opened 2021-11-10 22:42 UTC by EldaveO

##### Summary 

:memo: Addition of the gitmoji standard and creation of the contributing guidelines.
Reviewed using a markdown editor.
resolves #390 

##### Checklist

* [ ] this is a source code change
  * [ ] run `isort . && black .` in the repository root
  * [ ] run `pytest` in the repository root
  * [x] link to issue being fixed using a [_fixes keyword_](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue), if such an issue exists
  * [ ] update the wiki documentation if necessary
* [x] or, this is **not** a source code change

2021-11-10 22:55 UTC, twentylemon requested changes
You didn't even use an emoji in this pull request. Come on dude.

2021-11-10 22:55 UTC, twentylemon commented on .github/contributing_guidelines.md
> +#### Summary
This file does not have the correct name. See [docs](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors).

2021-11-10 22:55 UTC, twentylemon commented on .github/contributing_guidelines.md
> +##### Gitmoji standard
It's not really a _standard_, just something we're using.

2021-11-10 23:14 UTC, EldaveO commented on .github/contributing_guidelines.md
> +##### Gitmoji standard
Noted, I've updated the wording in the lasted commit to move away from the mention of a defined _standard_.

2021-11-10 23:15 UTC, EldaveO commented on .github/contributing_guidelines.md
> +#### Summary
Fixed it in my latest commit.
Thank you!

2021-11-11 00:37 UTC, twentylemon requested changes
Thinking more about this, I don't think `CONTRIBUTING` is the best place for this. We don't really want contributors and likely won't refer or add to these guidelines for that reason. Adding to the existing pull request template is sufficient for fixing #390, and more likely to serve as a reminder to people opening pull requests to actually add the emojis -- hiding them in `CONTRIBUTING` will lead to a lot of forgotten emojis.

Also,

> You didn't even use an emoji in this pull request. Come on dude.

Actually though.

2021-11-11 01:47 UTC, Chippers255 commented
bruh
> You didn't even use an emoji in this pull request. Come on dude.

2021-11-11 02:19 UTC, EldaveO commented
So for PRs the emojis should be in the tile rather than in the summary section.

Lesson learned.

2021-11-25 16:11 UTC, twentylemon commented
@EldaveO attaching `needs reply` label. Get some traction or it's getting yeeted.

2021-11-25 16:13 UTC, jameshughes89 commented
> Thinking more about this, I don't think `CONTRIBUTING` is the best place for this. We don't really want contributors and likely won't refer or add to these guidelines for that reason. **Adding to the existing pull request template is sufficient** for fixing #390, and more likely to serve as a reminder to people opening pull requests to actually add the emojis -- hiding them in `CONTRIBUTING` will lead to a lot of forgotten emojis.

+1 for template.

2021-12-20 18:25 UTC, jameshughes89 commented
I'm still down, but for a simpler, lightweight and minimalist version.

2022-01-24 21:54 UTC, EldaveO commented
Yeet away, I'll bring it back up when I get more time.

On Mon., Jan. 24, 2022, 6:22 a.m. github-actions[bot], <
***@***.***> wrote:

> Yo dawg, get some traction on this or it'll be yeeted. Brother.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/duck-dynasty/duckbot/pull/393#issuecomment-1020095743>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APDZ5IEBUARMLJTWXIFHWRTUXVHA7ANCNFSM5HZCESLA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-03-07 13:23 UTC, closed without merging