Dave and Graeme's birthday
duck-dynasty/duckbot pull request #644
Opened 2022-12-15 14:38 UTC by EldaveO

##### Summary

Included Graeme's and Dave's birthday dates
Fixes Issue #643

##### Checklist

- [x] this is a source code change
  - [ ] run `format` in the repository root
  - [ ] run `pytest` in the repository root
  - [x] link to issue being fixed using a [_fixes keyword_](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue), if such an issue exists
  - [ ] update the wiki documentation if necessary
- [ ] or, this is **not** a source code change

2022-12-15 14:39 UTC, jameshughes89 requested changes

2022-12-15 14:39 UTC, jameshughes89 commented on duckbot/cogs/announce_day/special_days.py
> +        self[date(year, 10, 21)] = f"G-dawg's Birthday. He is a glorious {year-1989} years old!"
I suggest putting it in order, like the rest of the dates.

2022-12-15 14:44 UTC, jameshughes89 commented
You need to also run `format`. 
![image](https://user-images.githubusercontent.com/1328048/207890154-0a6bca80-b025-47bc-8acb-b634eeb039ef.png)

2022-12-15 14:44 UTC, jameshughes89 commented
And also run `pytest` for good measure

2022-12-15 14:48 UTC, EldaveO commented
> You need to also run `format`. ![image](https://user-images.githubusercontent.com/1328048/207890154-0a6bca80-b025-47bc-8acb-b634eeb039ef.png)

How does one those commands?

2022-12-15 14:50 UTC, jameshughes89 commented
> > You need to also run `format`. ![image](https://user-images.githubusercontent.com/1328048/207890154-0a6bca80-b025-47bc-8acb-b634eeb039ef.png)
> 
> How does one those commands?

Do you have it setup locally? Or did you change it in the browser?

If you have it locally, just run the stuff at the top of the README:

```bash
python3.8 -m venv --clear --prompt duckbot venv
. venv/bin/activate
pip install --upgrade pip setuptools wheel
SETUPTOOLS_ENABLE_FEATURES="legacy-editable" pip install --editable .[dev]
```
and then
```bash
pytest  # runs tests, lint and format checks
format  # reformats the entire code base
```

2022-12-15 18:41 UTC, twentylemon requested changes

2022-12-15 18:41 UTC, twentylemon commented on duckbot/cogs/announce_day/special_days.py
> +        self[date(year, 12, 15)] = f"Dave's Birthday. He is 29 years old for the {year-2020} in a row"
This doesn't really read like english. I like the joke, but the wording needs improvement.

> 2023: _Dave's Birthday. He is 29 years old for the 3 in a row_
> 2024: _Dave's Birthday. He is 29 years old for the 4 in a row_

It should read:

> 2023: _Dave's Birthday. He is 29 years old for the 3rd year in a row_
> 2024: _Dave's Birthday. He is 29 years old for the 4th year in a row_

2022-12-15 19:11 UTC, twentylemon commented on duckbot/cogs/announce_day/special_days.py
> +        self[date(year, 10, 21)] = f"G-dawg's Birthday. He is a glorious {year-1989} years old!"
Bruh. This obviously isn't g-money's birth year. How could you possibly not be aware of this information.

2023-01-05 12:16 UTC, jameshughes89 commented on duckbot/cogs/announce_day/special_days.py
> +        self[date(year, 12, 15)] = f"Dave's Birthday. He is 29 years old for the {year-2020} in a row"
When discussing offline, @twentylemon suggested creating functionality to make the correct suffix for the number. E.g.

1 -> 1st
2 -> 2nd
3 -> 3rd
everything else 
X -> Xth

2023-01-12 23:57 UTC, twentylemon commented
Adding `needs-reply`. This will be automatically closed if there continues to be no traction on it.

2023-01-13 14:11 UTC, jameshughes89 commented on duckbot/cogs/announce_day/special_days.py
> +        self[date(year, 12, 15)] = f"Dave's Birthday. He is 29 years old for the {year-2020} in a row"
Any ideas on where this function would best live? Just in the `SpecialDays` class?

2023-01-13 14:16 UTC, twentylemon commented on duckbot/cogs/announce_day/special_days.py
> +        self[date(year, 12, 15)] = f"Dave's Birthday. He is 29 years old for the {year-2020} in a row"
Left as an exercise to the writer.

2023-01-14 23:14 UTC, EldaveO commented
Motivation is coming along. I think I can get some traction on it today.

2023-01-14 23:17 UTC, EldaveO commented on duckbot/cogs/announce_day/special_days.py
> +        self[date(year, 10, 21)] = f"G-dawg's Birthday. He is a glorious {year-1989} years old!"
This has been adjusted to 1988.

2023-01-14 23:20 UTC, EldaveO commented on duckbot/cogs/announce_day/special_days.py
> +        self[date(year, 12, 15)] = f"Dave's Birthday. He is 29 years old for the {year-2020} in a row"
I think to reduce the scope of this pull request I'll make the change to the birthdays and have it working in a reasonable state.

Then I'll make an issue for the adding the ``SpecialDays`` class. This is in an effort to insure we do not miss Graeme's birthday in the future.

2023-01-14 23:24 UTC, twentylemon commented on duckbot/cogs/announce_day/special_days.py
> +        self[date(year, 12, 15)] = f"Dave's Birthday. He is 29 years old for the {year-2020} in a row"
I disagree that the scope of the change need be reduced, it's already quite minimal. Two birthdays and a single function to add a number suffix is not large enough to warrant multiple pull requests.

2023-01-14 23:29 UTC, jameshughes89 commented on duckbot/cogs/announce_day/special_days.py
> +        self[date(year, 12, 15)] = f"Dave's Birthday. He is 29 years old for the {year-2020} in a row"
+1

This change would only get merged to _exist_ in an incomplete state before the full change actually occurs.

2023-02-06 14:56 UTC, jameshughes89 commented
:eyes:

2023-04-11 17:56 UTC, Chippers255 commented
Bump because I have faith in @EldaveO to finish this.

2023-05-22 13:19 UTC, closed without merging