Added functionality for bot to search for recipies
duck-dynasty/duckbot pull request #74
Opened 2021-02-26 20:22 UTC by Chippers255

This satisfies a part of issue #13. The !recipe command will now exist on all channels allowing people to search allrecipes.

2021-02-26 20:33 UTC, twentylemon commented
Please fix lint errors. See [checks](https://github.com/Chippers255/duckbot/runs/1990475953?check_suite_focus=true).

2021-02-26 20:43 UTC, twentylemon requested changes
Good stuff overall.

2021-02-26 20:43 UTC, twentylemon commented on duckbot/cogs/recipe.py
> +    def search(search_term):
This method should be broken down, it's doing a lot of work. I'd probably do three methods to make this easier to understand:
* fetch recipes for a search term
* select a single recipe given a collection
* send a recipe card to the channel

2021-02-27 22:19 UTC, Chippers255 commented
Marked as draft, I need to fix the linting errors and write a couple more tests on the command method.

2021-02-28 19:00 UTC, twentylemon approved these changes
Good stuff, brother.

2021-02-28 19:01 UTC, merged